language: node_js
node_js:
- '4.5'
script:
- npm test
- npm run lint
after_script:
- npm run codecov
notifications:
  email: false
  slack:
    secure: iJuglKHAdixUuyRWPNDiCtFQZ2uQLAqtenCBYHF1SxEB4ukZCUtRhSrcrYrmppvNE0A0RHOi2hdd002I7gfOKGXs0Q/IUDmIrX63jt93hlQByDUG8KzOvriMnbXcwvpkABjCwMwKrXrXWadpMp35axrqZXA8WrZ05aA3fpI/3IzSU5KNb4Wd1TDfDdl82v6t8tvuYubGJQVnEp3k+oPHttcjqcrUzldJr3iw3+eIAu/aygsOB2EgFvntjUX/g4FSJBb1rgwZH4iXmewqYKGmARUZ4hmDPkxSOUqZPXXWSBs5Efu99UXt0ujs9Chzi0xZbjGHadGoaAanqua4lmnQ8i9V0kZNU6ORXX9jD2sQN5Vd5Ye05dtg2DxxSLqOIa165FfO+fESJzIGnL3wHDiL6oQlRcdCYzHM0Akdfdj6v+LUhYoMXTPoDJsA1/Bk2GY5bOG1ftx2cu9ILfLEZmy/KS5ZiwVd7fA/75cQUVWOn43rvDATAnkhg32h9T0m3/uI01ifVFhzdraVEp8ueLmIzh/o26NpX3DK9tPBJbRHFXNNRObwXERb/LE+SMMJ7h2TEtGuO69+3TaQSXNFop+izauMsfSQQfQ6sn/lVPv87a7aXFhYQLfLQmiR9x++oC/B7HGNrJd5aIdsDAJ6hl0r4EYGhGSJCfanm5iHmACUd70=
